/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/KfP9o0cl4XD
 */
import Link from "next/link"

export function herof() {
  return (
    (<section className="w-full py-12 md:py-24 lg:py-32 xl:py-48">
      <div className="container px-4 md:px-6">
        <div className="flex flex-col items-center space-y-4 text-center">
          <div className="space-y-2">
            <h1
              className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none">
              Design. Ship. Innovate.
            </h1>
            <p
              className="mx-auto max-w-[600px] text-gray-500 md:text-xl dark:text-gray-400">
              The platform for modern design workflows. Create the best user experiences. Collaborate seamlessly. Ship
              faster.
            </p>
          </div>
          <div className="space-x-4 flex flex-col md:flex-row items-center">
            <Link
              className="inline-flex w-full md:w-auto h-9 items-center justify-center rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
              href="#">
              Get Started
            </Link>
          </div>
        </div>
      </div>
    </section>)
  );
}
